spring:
  data:
    mongodb:
      uri: mongodb+srv://sourabhchhikara1313_db_user:Sourabh1313@sourabh.dnbgcz6.mongodb.net/journaldb?appName=Sourabh
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal
